version: '3.8'

services:
  app:
    build:
      context: .  # Diretório onde está o Dockerfile
      dockerfile: Dockerfile  # Nome do Dockerfile (pode ser omitido se for 'Dockerfile')
    restart: unless-stopped
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      -'80:80' #http 
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.4"
          memory: 2062M
    networks:
      - npm_public

volumes:
  npm_data:
    external: true
  npm_letsencrypt:
    external: true

networks:
  npm_public:
    external: true
